# Generated by Django 6.0.8 on 2026-08-05 11:18

import bookings.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text="Value the website form submits, e.g. 'hot-stone'", unique=True)),
                ('name', models.CharField(max_length=120)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from the booking form')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(default=bookings.models.generate_booking_id, editable=False, max_length=32, unique=True)),
                ('full_name', models.CharField(max_length=150, verbose_name='full name')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('service_name', models.CharField(blank=True, help_text='Snapshot at time of booking', max_length=120)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Snapshot at time of booking', max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('date', models.DateField(verbose_name='preferred date')),
                ('time', models.TimeField(verbose_name='preferred time')),
                ('therapist', models.CharField(blank=True, default='No preference', max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], default='CONFIRMED', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Staff only — not shown to the customer')),
                ('consent_given', models.BooleanField(default=False)),
                ('captcha_verified', models.BooleanField(default=False)),
                ('source_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['date', 'time'], name='bookings_bo_date_9ed98b_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx')],
            },
        ),
    ]
