# Generated by Django 6.1 on 2026-08-20 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_contactmessage_waitlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='agent_reply',
            field=models.TextField(blank=True, help_text='The message the agent sent back to the customer.'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='email_preview',
            field=models.TextField(blank=True, help_text='The notification email content. Shown here while email sending is a dummy/stub; once EMAIL_HOST is configured in settings.py this is only a copy of what was really sent.'),
        ),
        migrations.DeleteModel(
            name='Waitlist',
        ),
    ]
