# Generated by Django 6.1 on 2026-08-20 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_contactmessage_agent_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='related_booking',
            field=models.ForeignKey(blank=True, help_text='The booking this message ended up changing, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='requested_date',
            field=models.DateField(blank=True, help_text='The new date the customer asked for, if this was a reschedule request.', null=True),
        ),
    ]
